# Generated by Django 2.2.4 on 2020-08-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200807_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='foto_ads')),
                ('text', models.TextField()),
                ('link', models.CharField(max_length=10000)),
            ],
        ),
    ]
