# Generated by Django 2.2.4 on 2020-08-07 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_ads'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Recomment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField()),
                ('likes', models.IntegerField()),
                ('own', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Users')),
            ],
        ),
    ]
