# Generated by Django 2.2.4 on 2020-08-07 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200807_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
