# Generated by Django 2.2.4 on 2020-08-08 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200807_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='likes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recomment',
            name='likes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
