# Generated by Django 2.2.4 on 2020-08-08 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200808_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date_send',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='recomment',
            name='date_send',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
