# Generated by Django 2.2.4 on 2020-08-11 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_ads_is_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
